//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 09:42:31 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo;
