//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.22 at 09:26:28 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo;
